### ISSUE TITLE
Please more precise install information.

### ISSUE THREAD

**Issue by COLABORATI** [sagarchalise/geanypy-emmet#3]
Would you like to please explain more exactly how to install this plugin? 
* To which directory do I have to git clone this repo?
* How do I determine if I need gtk2 or gtk3? And what exactly does 'use' mean in each case? Not use this repo or do something else with it? It is unclear.
* There are 2 different versions of pyV8 binaries - for Sublime 2 and for Sublime 3 - which one to use?

A reproducible installation instruction for e.g. Ubuntu Trusty will be very appreciated!

(I just want to use emmet in geany, not dive into geany internals)

Thanks!

**Comment by sagarchalise** [comment]
You can clone this repo any where you like. Since, I use it with ubuntu, I am going to explain on basis of ubuntu itself.

- Clone it anywhere. You need to copy `geanypy-emmet.py` and `editor.js` to geany plugin directory. 
- Gtk2 and Gtk3 is determined by how you installed geany and what os you use. By default geany uses gtk2 and gtk3 is experimental support that can be installed only if you build it yourself.
- pyv8 binaries are dependent on python version. Since, geanypy uses python2, you have to use pyv8 binary for python 2. Also, it will depend on what os architecture you have basically a 64 bit OS will need https://github.com/emmetio/pyv8-binaries/blob/master/pyv8-linux64.zip and 32 bit linux OS will need https://github.com/emmetio/pyv8-binaries/blob/master/pyv8-linux32.zip

See if the latest readme is clear.

**Comment by COLABORATI** [comment]
OMG, thank you, got it working - how great to finally have emmet in geany! What a day!
One more question (pedantic): is there a way to have all the files in one subdirectory of ```$HOME/.config/geany/plugins```? Currently I have to put all the files directly in that directory, however with one subdirectory of e.g. ```ganypy-emmet``` it would be a little bit cleaner. 
Not important, just pedantic sugar. However, thanks for this, emmet was the only thing I was always missing in geany!

**Comment by sagarchalise** [comment]
I think the plugins are loaded from either geany plugins from system or config so you cannot atleast bundle `geanypy-emmet.py` inside a folder other than plugins. One approach would be bundling `emmet`, `_PyV8.so` and `PyV8.py` and `editor.js` in one directory and using that directory as module[But that would require code changes]
